### ISSUE TITLE
Bytes had change variable name from findIndex to Index of

### ISSUE THREAD

**Issue by chgara** [vslinko/deno-readline#1]
error: TS2305 [ERROR]: Module '"https://deno.land/std@0.83.0/bytes/mod.ts"' has no exported member 'findIndex'.
export { concat, findIndex } from "https://deno.land/std/bytes/mod.ts";

I saw in the code that findIndex has been changed to indexOf. I'll submit a pull request.

**Comment by vslinko** [comment]
Thank your for your contribution! Released as [v1.1.0](https://deno.land/x/readline@v1.1.0)
